spring:
  #  datasource:
  #    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
  #    url: jdbc:log4jdbc:mysql://210.122.3.31:3306/new_center?serverTimezone=UTC&characterEncoding=EUC-KR&zeroDateTimeBehavior=convertToNull
  #    username: root
  #    password: devdbsuper2015!@#

  #    driver-class-name: com.mysql.jdbc.Driver
  #    url: jdbc:mysql://210.122.3.31:3306/new_center?serverTimezone=UTC&characterEncoding=EUC-KR&zeroDateTimeBehavior=convertToNull
  #    username: rlvdms
  #    password: todrkr122

  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:mysql://localhost:3306/photogram?serverTimezone=Asia/Seoul&useSSL=false
    username: root
    password: kanggeol00

  devtools:
    add-properties: false

  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp

logging:
  dir: ./logs

jwt:
  header: Authorization
  secret: "E/v]Goy<d,F$}Vg-ZM\thOOsPZAILA,'Xq{?wyDHyFI`qpux;ob-j>Ogk<Hn/^Q:"

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.dailystudy.dtmsapi.domain

servet:
  multipart:
    enabled: true
    max-file-size: 2MB

file:
  path: Users/kanggeol/Downloads/
